### ISSUE TITLE
Verify creator on create if signer

### ISSUE THREAD

**Issue by joefitter** [nifty-oss/asset#57]
If the creator is a signer, then they could be verified on creating the asset.

https://github.com/nifty-oss/asset/blob/252fbba136b6a6b213d606501a4ce37030a7fb25/programs/asset/types/src/extensions/creators.rs#L74

Currently if you create a new asset with a creator which is also the authority, it will remain unverified unless a separate verify instruction is called

**Comment by febo** [comment]
Good call, I prepared a PR to add this.
